services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: url_user
      POSTGRES_PASSWORD: url_pass
      POSTGRES_DB: url_shortener
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    restart: on-failure
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://url_user:url_pass@db:5432/url_shortener"
      JWT_SECRET: "vasco"
      BASE_URL: "http://localhost:3000"
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: url_user
      DB_PASSWORD: url_pass
      DB_DATABASE: url_shortener
    depends_on:
      - db

volumes:
  pgdata:
